load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "python_package_smoke_test",
    srcs = ["python_package_smoke_test.py"],
    data = [
        "//:hayaku/core.py",
        "//:hayaku_ingest_native/__init__.py",
        "//:hayaku_realtime_native/__init__.py",
        "//hayaku_cpp/src:core_shared",
        "//hayaku_cpp/src:ingest_shared",
        "//hayaku_cpp/src:realtime_shared",
        "//hayaku_pywrap:core310",
        "//hayaku_pywrap:ingest310",
        "//hayaku_pywrap:realtime310",
    ],
    size = "large",
)
