#pragma once

#include "common/OsDef.h"

#define HAYAKU_ENABLE_MYSQL 0
#define HAYAKU_DISABLE_LIBMYSQLCLIENT 0
#define HAYAKU_ENABLE_SQLITE 1
#define HAYAKU_ENABLE_SQLCIPHER 0
#define HAYAKU_SUPPORT_DATETIME 1
#define HAYAKU_ENABLE_INI_PARSER 1
#define HAYAKU_ENABLE_STACK_TRACE 0
#define HAYAKU_CLOSE_SPEND_TIME 0
#define HAYAKU_USE_SPDLOG_ASYNC_LOGGER 0
#define HAYAKU_LOG_ACTIVE_LEVEL 2
#define HAYAKU_ENABLE_HTTP_CLIENT 1
#define HAYAKU_ENABLE_HTTP_CLIENT_SSL 0
#define HAYAKU_ENABLE_HTTP_CLIENT_ZIP 0
#define HAYAKU_ENABLE_NODE 1
