#pragma once

/*
 * SpendTimer.h
 *
 *  Copyright (c) 2019 hikyuu.org
 *
 *  Created on: 2019-6-15
 *      Author: fasiondog
 */

#ifndef NOMINMAX
#define NOMINMAX
#endif

#include <fmt/format.h>

#include <chrono>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <vector>

#include "common/Config.h"

#ifndef HAYAKU_UTILS_API
#define HAYAKU_UTILS_API
#endif
#ifdef __ANDROID__
#include <android/log.h>
#endif

#ifdef __APPLE__
#include <TargetConditionals.h>
#endif

#ifdef _WIN32
#include <shlwapi.h>
#pragma comment( \
    lib, "shlwapi.lib")  // The library needed when linking under Windows
#define GET_FILENAME(path) PathFindFileNameA(path)
#else
#include <libgen.h>
#define GET_FILENAME(path) basename((char *)path)
#endif

#ifndef HAYAKU_CLOSE_SPEND_TIME
#define HAYAKU_CLOSE_SPEND_TIME 1
#endif

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4834)
#endif

#ifdef __GNUC__
// Turn off the warning generated by the line using _Base::_Base;
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat-security"
#endif

namespace hayaku {

/**
 * @ingroup Utilities
 * @addtogroup SpendTimer Spend timer time consumption statistics
 * @details The utility macros assisting in the statistics of the execution time
 * of a code block; they can be turned off at compile time with the macro
 * HAYAKU_CLOSE_SPEND_TIME=1, or turned on with HAYAKU_CLOSE_SPEND_TIME=0
 * @code
 *     {
 *        SPEND_TIME(test, "run test");
 *        ...
 *     }
 * @endcode
 * @{
 */
#if HAYAKU_CLOSE_SPEND_TIME
#define SPEND_TIME(id)
#define SPEND_TIME_MSG(id, ...)
#define SPEND_TIME_KEEP(id, ...)
#define SPEND_TIME_SHOW(id)
#define SPEND_TIME_VALUE(id)
#define BENCHMARK_TIME(id, cycle)
#define BENCHMARK_TIME_MSG(id, cycle, ...)
#define SPEND_TIME_CONTROL(open)
#define OPEN_SPEND_TIME
#define CLOSE_SPEND_TIME

#else /* #if HAYAKU_CLOSE_SPEND_TIME */
/**
 * Timer for the time consumption of the code execution
 * @param id the custom time consumption timer id
 */
#define SPEND_TIME(id)                                                  \
  hayaku::SpendTimer test_spend_timer_##id(#id, GET_FILENAME(__FILE__), \
                                           __LINE__);

/**
 * Timer for the time consumption of the code execution, with an output message
 * @param id the custom time consumption timer id
 * @param ... the output message
 */
#define SPEND_TIME_MSG(id, ...)                                   \
  std::string msg_##id(fmt::format(__VA_ARGS__));                 \
  hayaku::SpendTimer test_spend_timer_##id(#id, msg_##id.c_str(), \
                                           GET_FILENAME(__FILE__), __LINE__);

/** Stopwatch timing */
#define SPEND_TIME_KEEP(id, ...) \
  test_spend_timer_##id.keep(fmt::format(__VA_ARGS__));

/** Display the current time consumption */
#define SPEND_TIME_SHOW(id) test_spend_timer_##id.show();

/** Get the number of the seconds consumed from the start to the current */
#define SPEND_TIME_VALUE(id) test_spend_timer_##id.value()

/**
 * Used to dynamically control the time consumption timers in the current code
 * block and its sub-blocks; it is mainly used to turn off and on a part of the
 * time consumption statistics in the test code
 */
#define SPEND_TIME_CONTROL(open) \
  hayaku::SpendTimerGuad spend_timer_guard_##open(open);

/** Globally turn on the message time consumption printing */
#define OPEN_SPEND_TIME hayaku::open_spend_time()

/** Globally turn off the message time consumption printing */
#define CLOSE_SPEND_TIME hayaku::close_spend_time()

/**
 * Benchmark time consumption timer
 * @param id the custom time consumption timer id
 * @param cycle  the number of the loop runs (used for the statistics printing
 * output only)
 */
#define BENCHMARK_TIME(id, cycle)                                       \
  hayaku::SpendTimer test_spend_timer_##id(#id, GET_FILENAME(__FILE__), \
                                           __LINE__);                   \
  test_spend_timer_##id.setCycle(cycle);

/**
 * Benchmark time consumption timer, with an output message
 * @param id the custom time consumption timer id
 * @param cycle  the number of the loop runs (used for the statistics printing
 * output only)
 * @param ... the output message
 */
#define BENCHMARK_TIME_MSG(id, cycle, ...)                                    \
  std::string msg_##id = fmt::format(fmt::runtime(__VA_ARGS__));              \
  hayaku::SpendTimer test_spend_timer_##id(#id, msg_##id.c_str(),             \
                                           GET_FILENAME(__FILE__), __LINE__); \
  test_spend_timer_##id.setCycle(cycle);

#endif /* HAYAKU_CLOSE_SPEND_TIME */

/**
 * Timer for the statistics of the program execution time consumption, it
 * assists in calculating the code execution time
 * @note It is not recommended to use it directly, the related utility macros
 * should be used
 * @see SPEND_TIME, SPEND_TIME_MSG, SPEND_TIMG_CONTROL
 */
class HAYAKU_UTILS_API SpendTimer {
 public:
  /** Constructor, it records the current system time */
  explicit SpendTimer()
      : cycle_(1),
        msg_(""),
        lineno_(0),
        start_time_(std::chrono::steady_clock::now()),
        pre_keep_time_(start_time_) {}

  /**
   * Constructor, it records the current system time
   * @param id timer id
   * @param filename the current file name, corresponding to __FILE__
   * @param lineno the current line number, corresponding to __LINE__
   */
  explicit SpendTimer(const char *id, const char *filename, int lineno)
      : cycle_(1),
        id_(id),
        msg_(""),
        filename_(filename),
        lineno_(lineno),
        start_time_(std::chrono::steady_clock::now()),
        pre_keep_time_(start_time_) {}

  /**
   * Constructor, it records the current system time
   * @param id timer id
   * @param msg the additional output message
   * @param filename the current file name, corresponding to __FILE__
   * @param lineno the current line number, corresponding to __LINE__
   */
  explicit SpendTimer(const char *id, const char *msg, const char *filename,
                      int lineno)
      : cycle_(1),
        id_(id),
        msg_(msg),
        filename_(filename),
        lineno_(lineno),
        start_time_(std::chrono::steady_clock::now()),
        pre_keep_time_(start_time_) {}

  /** Destructor, it calculates the time consumed from the construction to the
   * destruction and prints the output */
  virtual ~SpendTimer();

  /**
   * @brief Get the time consumed from the start to the current moment, in
   * seconds
   * @return std::chrono::duration<double>
   */
  std::chrono::duration<double> duration() const {
    return std::chrono::steady_clock::now() - start_time_;
  }

  /** Print the time consumed from the start of the timer until now, and return
   * the current consumed seconds */
  void show() const;

  /** Get the number of the seconds consumed from the start to the current */
  double value() const;

  /**
   * @brief Stopwatch timing; every keep records the interval between the
   * current time and the last keep
   * @param description description
   * @note The first keep is the interval between the current time and the start
   */
  void keep(const std::string &description);

  /**
   * @brief Get the stopwatch timing list
   * @return const std::vector<std::chrono::duration<double>>&
   */
  const std::vector<std::chrono::duration<double>> &getKeepDurations() const {
    return keep_seconds_;
  }

  /**
   * Tell the number of the loops in the benchmark test
   * @param cycle the number of the loops, used for the time consumption
   * statistics printing only
   */
  void setCycle(int cycle) { cycle_ = cycle; }

 public:
  /** Get the current switch state of the time consumption printing */
  static bool isClosed() { return ms_closed; }

 private:
  int cycle_;  // Tells the number of the loops in the benchmark test
  std::string id_;
  std::string msg_;
  std::string filename_;
  int lineno_;
  std::chrono::time_point<std::chrono::steady_clock> start_time_;
  std::chrono::time_point<std::chrono::steady_clock> pre_keep_time_;
  std::vector<std::chrono::duration<double>> keep_seconds_;
  std::vector<std::string> keep_desc_;

  static bool ms_closed;
  friend void HAYAKU_UTILS_API close_spend_time();
  friend void HAYAKU_UTILS_API open_spend_time();
  friend bool HAYAKU_UTILS_API get_spend_time_status();
};

/** Globally turn off the time consumption printing output */
void HAYAKU_UTILS_API close_spend_time();

/** Globally turn on the time consumption printing output */
void HAYAKU_UTILS_API open_spend_time();

/** Get the global state of the time consumption printing output: true - on,
 * false - off */
bool HAYAKU_UTILS_API get_spend_time_status();

/**
 * A guard of the on/off state of the time consumption timer; it records the
 * previous switch state and sets it to the given state, restoring the original
 * state on release
 */
class SpendTimerGuad {
 public:
  /**
   * Constructor, it records the current state and turns on or off the time
   * consumption statistics according to open
   * @param open whether to turn on the time consumption statistics
   */
  explicit SpendTimerGuad(bool open) : open_(open), old_open_(false) {
    old_open_ = !SpendTimer::isClosed();
    if (open_ == old_open_) {
      return;
    }
    if (open_) {
      open_spend_time();
    } else {
      close_spend_time();
    }
  }

  /** Destructor, it exits the given state and restores the original state */
  ~SpendTimerGuad() {
    if (open_ == old_open_) {
      return;
    }
    if (old_open_) {
      open_spend_time();
    } else {
      close_spend_time();
    }
  }

 private:
  bool open_;
  bool old_open_;
};

/** @} */

} /* namespace hayaku */

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif

#ifdef _MSC_VER
#pragma warning(pop)
#endif
