#pragma once

// Bazel's default macOS/Linux feature set.
#define HAYAKU_DEBUG_MODE 0
#define HAYAKU_LOCAL_VECTORIZE 0
#define HAYAKU_SUPPORT_SERIALIZATION 1
#define HAYAKU_SUPPORT_TEXT_ARCHIVE 1
#define HAYAKU_SUPPORT_XML_ARCHIVE 1
#define HAYAKU_SUPPORT_BINARY_ARCHIVE 1
#define CHECK_ACCESS_BOUND 1
#define ENABLE_MSVC_LEAK_DETECT 0
#define HAYAKU_ENABLE_LEAK_DETECT 0
#define HAYAKU_ENABLE_SEND_FEEDBACK 0
#define HAYAKU_ENABLE_HDF5_KDATA 1
#define HAYAKU_ENABLE_MYSQL_KDATA 0
#define HAYAKU_ENABLE_SQLITE_KDATA 1
#define HAYAKU_ENABLE_TDX_KDATA 1
#define HAYAKU_USE_LOW_PRECISION 0
#define HAYAKU_ENABLE_TA_LIB 1
#define HAYAKU_ENABLE_MIMALLOC 0
