#pragma once

#define HAYAKU_VERSION "2.8.2"
#define HAYAKU_VERSION_MAJOR 2
#define HAYAKU_VERSION_MINOR 8
#define HAYAKU_VERSION_ALTER 2
#define HAYAKU_VERSION_BUILD 0
#define HAYAKU_VERSION_MODE "RELEASE"
#define HAYAKU_VERSION_GIT "2.8.2 (bazel)"
